[package]
name = "orbital-vertices"
version = "0.1.0"
edition = "2021"

[lib]
name = "orbital_vertices"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module"] }
rand = "0.8"
num-complex = "0.4"